name: boilerplate_getx
version: 1.0.0+1
publish_to: none
description: Flutter Boilerplate GetX
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: 1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: 8.2.5
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.2
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svg_image/
    - assets/animations/

